version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=nham  
      - POSTGRES_PASSWORD=nham
      - POSTGRES_DB=nham_dev
      - DATABASE_HOST=postgres 
    ports:
      - '5432:5432'
    networks:
      - nham-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: nham@admin.com
      PGADMIN_DEFAULT_PASSWORD: nham
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - nham-network
    restart: unless-stopped  

networks:
  nham-network:
    driver: bridge

